name: Build and publish

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: all-space-matei/cmake-build

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - run: buildah --version

      - name: Build
        id: build-image
        run: >-
            buildah build
            -t ${{ env.IMAGE_NAME }}:latest
            -t ${{ env.IMAGE_NAME }}:v1
            -t ${{ env.IMAGE_NAME }}:${{ github.sha }}
            -f Containerfile

      - name: Push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest v1 ${{ github.sha }}
          registry: ${{ env.REGISTRY }}
